language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
script: "./build.sh"
notifications:
  slack: 
    rooms:
      - agile-irb-bnp:e9CI9Ro3wL3KjJbRSwwVWy1Z#skool-boomer
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"  